version: '3'

services:
  nginx:
    container_name: telegram-nginx
    image: nginx:1.20.2
    restart: always
    volumes:
      - ./volumes/html:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/templates
    depends_on:
      - php
    links:
      - php
    ports:
      - "${COMPOSE_NGINX_PORT}:80"
  php:
    container_name: telegram-php
    build:
      context: ./docker/images/php
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./volumes/html:/var/www/html
    links:
      - mysql
  mysql:
    container_name: telegram-mysql
    image: mysql:8
    restart: always
    volumes:
      - ./docker/db/mysql/dump:/docker-entrypoint-initdb.d
      - ./docker/db/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${COMPOSE_MYSQL_PORT}:3306"
